GET http://localhost:3000/admin
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzkwMjIsInJvbGVzIjpbImFkbWluIl19.KVlA6xWEqnxhjEMh64auVe9RsjwQhRqNcjiFl1992ls